### ISSUE TITLE
Supported media file types / extensions

### ISSUE THREAD

**Issue by PatMyron** [dabutvin/ImgBot#332]
It looks like these are the currently supported file extensions:

https://github.com/dabutvin/ImgBot/blob/392f7b20e4117e363b78e2537e4d915cabefcc26/Common/KnownImgPatterns.cs#L5

It'd be awesome to have support for additional formats like [.svg](https://github.com/dabutvin/ImgBot/issues/56), .pdf, and audio+video formats like .mp4

**Comment by dabutvin** [comment]
hey @PatMyron 
Would love to see imgbot expanding out like this.

I had this thought the other day about svgs, but couldn't find a good dotnet optimizer for them and I naively started my own (https://github.com/dabutvin/SvgClean)

I bet we can find existing optimizers for videos + pdfs though! I hadn't considered them before.
Do you have any suggestions for optimizers for any of these file types?

**Comment by PatMyron** [comment]
Definitely worth further research, but FFmpeg looks like an option

**Comment by geeknoid** [comment]
I recommend integrating with https://github.com/svg/svgo which does an excellent job in crunching down SVGs. It'd be great to have ImgBot take care of those.

**Comment by dabutvin** [comment]
@geeknoid that would be really cool. I wonder what the best way to fit that into the rest of the compression workflow would be, given that svgo is all JavaScript

**Comment by geeknoid** [comment]
svgo can run on a specific file, on a specific directory, or on a specific directory recursively.

I don't know how ImgBot is put together, but if I were to hack this together, I'd just kick off "svgo -r -f <repo dir>" as an external command. Any file it modifies, you include in the PR you post.

Now to run svgo, you would need to install it (npm install svgo -g) and then use the npx tool with it (npx svgo <args>). If this isn't working for some reason, an alternate solution is to create a docker image that contains svgo and use 'docker run' to execute it.

**Comment by dabutvin** [comment]
makes sense @geeknoid 👍 

I just opened #341 which would make this a lot more feasible - along with some potential performance improvements

**Comment by dabutvin** [comment]
It would be great to get svgo runnable as an executable, alternatively we would have to install node on the container - might not be so bad

**Comment by dabutvin** [comment]
just opened #386 to start adding svg support with svgo.
There's some more work to do, but it's a start

**Comment by PatMyron** [comment]
bump

**Comment by PatMyron** [comment]
@dabutvin could you re-open this?

**Comment by dabutvin** [comment]
SVG support is in!!!!

**Comment by dabutvin** [comment]
see #488 for an example of an issue for adding a new compression library.
We can use the same template for adding whole new file extensions.

**Comment by Matt-Gleich** [comment]
Any update of pdf compression? It would be really nice for people that use LaTex.

**Comment by dabutvin** [comment]
Hi @Matt-Gleich !

I'm totally cool with adding pdf compression. You recommend any libraries or tools that we should look at?

**Comment by Matt-Gleich** [comment]
A quick DuckDuckGo search brought up some useful tutorials on how to compress PDFs in C#

https://duckduckgo.com/?q=how+to+compress+pdfs+with+c%23&atb=v181-1&ia=web

**Comment by karlhorky** [comment]
@dabutvin is this project still being actively developed in 2023? I would be interested in the PDF compression/optimization support - is this already an accepted feature and just needs someone to take time to implement PDF compression in C#? Would guess that there would be libraries for this too... 🤔

**Comment by karlhorky** [comment]
Alternative: I've also created an issue in the GitHub issues for [Calibre Image Actions](https://github.com/marketplace/actions/image-actions):

- https://github.com/calibreapp/image-actions/issues/179

**Comment by karlhorky** [comment]
## Alternative 2

A separate GitHub Actions workflow to do this using `ghostscript` (generate an access token for this and add it as a GitHub repo secret called `PDF_COMPRESSION_GITHUB_TOKEN`):

```yaml
name: Compress PDFs
on:
  pull_request:
    # Run only when PDF files are added or changed
    paths:
      - '**.pdf'

jobs:
  build:
    # Only run on Pull Requests within the same repository, and not from forks.
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Compress PDFs
    runs-on: ubuntu-latest
    steps:
      - name: Run apt update
        run: sudo apt update
      - name: Install Ghostscript for compression
        run: sudo apt install -y ghostscript
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Compress PDFs
        run: |
          find . -type f -iname '*.pdf' -not -path "./node_modules/*" | while read file; do
            # Compress the file for screen using Ghostscript
            gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile="$file" "$file"
          done
      - name: Commit files
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          
          # Discard modified compressed files that are not more
          # than 10KB smaller than the previous version
          git ls-files -z --modified '*.pdf' | while IFS= read -r -d '' file; do
            old_size=$(git cat-file -s "HEAD:$file")
            new_size=$(wc -c < "$file" | tr -d ' ')
            if [[ $(($old_size - $new_size)) -lt 10000 ]]; then
              echo "Discarding changes to $file, new size $new_size not more than 10KB smaller than old size $old_size"
              git checkout -- "$file"
            fi
          done

          git add **/*.pdf
          git commit -m "Compress PDFs"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.PDF_COMPRESSION_GITHUB_TOKEN }}
```
