### ISSUE TITLE
Imgbot commits as?

### ISSUE THREAD

**Issue by kenman345** [dabutvin/ImgBot#84]
hey,

I wanted to exclude some stuff in my travis builds for imgbot by sender name with the jobs. And run only 1 stage for imgbot PR's

This is what I have in my `.travis.yml`:

```yml
stages:
  - name: Test
    if: sender != ImgBotApp
  - name: imgbot
    if: sender = ImgBotApp
```

Is the name of the user imgbot[bot]? because these rules are not working

**Comment by dabutvin** [comment]
The commit author is always set to ImgBotApp, but I am guessing the 'sender' is the one that opens the PR?

The call to GitHub to open the PR is made on behalf of the imgbot installation with a username set to 'x-access-token' and the password set to the installation token.

See https://imgbot.net/docs#authorization for more info :)

**Comment by kenman345** [comment]
so found out the answer:
```yml
  - name: Test
    if: sender != svenfuchs AND sender != imgbot[bot]
  - name: imgbot
    if: sender IN (svenfuchs, imgbot[bot])
```

Take a look at the login on the commit and then on the PR triggers of the builds:
PR: https://api.travis-ci.org/v3/build/357392655
Push: https://api.travis-ci.org/v3/build/357392715
